[project]
name = "hathora-pipecat-deployment"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "loguru>=0.7.3",
    "pipecat-ai[daily,openai,silero]>=0.0.82",
    "python-dotenv>=1.1.1",
    "uvicorn>=0.35.0",
]
